## [Practice Exercise: Analyzing Customer Data](#)

You are working with customer data for an e-commerce company. The data includes customer IDs, ages, and purchase amounts. Your task is to create NumPy arrays to store and analyze this data.

1. Create a 1-dimensional NumPy array called `customer_ids` that contains the following customer IDs: 1001, 1002, 1003, 1004, 1005.

2. Create a 1-dimensional NumPy array called `ages` that contains the ages of the customers: 25, 30, 35, 40, 45. Use the `np.arange()` function to create this array.

3. Create a 2-dimensional NumPy array called `purchase_amounts` that contains the purchase amounts for each customer over three months:
   - Month 1: 100, 200, 300, 400, 500
   - Month 2: 150, 250, 350, 450, 550
   - Month 3: 200, 300, 400, 500, 600

4. Create a 3-dimensional NumPy array called `sales_data` that combines the customer IDs, ages, and purchase amounts. The shape of the array should be (5, 3, 2), where:
   - The first dimension represents the customers
   - The second dimension represents the months
   - The third dimension represents the customer ID and age for each customer

5. Create a NumPy array called `large_purchases` that contains the purchase amounts greater than 300. Use boolean indexing to create this array.

6. Create a random integer array called `random_purchases` with shape (3, 5) that represents random purchase amounts between 100 and 1000.


### [Solution](#)


1. Creating the `customer_ids` array:

In [ ]:
import numpy as np

customer_ids = np.array([1001, 1002, 1003, 1004, 1005])

2. Creating the `ages` array using `np.arange()`:

In [ ]:
ages = np.arange(25, 50, 5)
ages

array([25, 30, 35, 40, 45])

3. Creating the `purchase_amounts` array:

In [ ]:
purchase_amounts = np.array([[100, 200, 300, 400, 500],
                             [150, 250, 350, 450, 550],
                             [200, 300, 400, 500, 600]])

4. Creating the `sales_data` array:

In [ ]:
sales_data = np.array([
    [[customer_ids[i], ages[i]] for i in range(5)],
    [[customer_ids[i], purchase_amounts[0][i]] for i in range(5)],
    [[customer_ids[i], purchase_amounts[1][i]] for i in range(5)],
    [[customer_ids[i], purchase_amounts[2][i]] for i in range(5)]
])
sales_data

array([[[1001,   25],
        [1002,   30],
        [1003,   35],
        [1004,   40],
        [1005,   45]],

       [[1001,  100],
        [1002,  200],
        [1003,  300],
        [1004,  400],
        [1005,  500]],

       [[1001,  150],
        [1002,  250],
        [1003,  350],
        [1004,  450],
        [1005,  550]],

       [[1001,  200],
        [1002,  300],
        [1003,  400],
        [1004,  500],
        [1005,  600]]])

5. Creating the `large_purchases` array using boolean indexing:

In [ ]:
large_purchases = purchase_amounts[purchase_amounts > 300]
large_purchases

array([400, 500, 350, 450, 550, 400, 500, 600])

6. Creating the `random_purchases` array with random integers:

In [ ]:
random_purchases = np.random.randint(100, 1000, size=(3, 5))
random_purchases

array([[231, 544, 936, 643, 317],
       [926, 176, 976, 711, 589],
       [306, 446, 953, 734, 107]])

In this exercise, we used various NumPy array creation functions and techniques to analyze customer data:

1. `np.array()` was used to create the `customer_ids` array from a list of customer IDs.
2. `np.arange()` was used to create the `ages` array with a specified start, stop, and step value.
3. `np.array()` with nested lists was used to create the `purchase_amounts` array representing purchase amounts for each customer over three months.
4. A combination of indexing and list comprehension was used to create the `sales_data` array, which combines customer IDs, ages, and purchase amounts in a 3-dimensional structure.
5. Boolean indexing was used to create the `large_purchases` array, selecting purchase amounts greater than 300.
6. `np.random.randint()` was used to create the `random_purchases` array with random integer values between 100 and 1000.
