## [Practice Exercise: Analyzing Temperature Data](#)

You are given a NumPy array `temperatures` that contains the daily temperature readings for a city over a period of one week. The array has shape `(7, 24)`, representing 7 days and 24 hourly temperature readings per day.


In [ ]:
import numpy as np

temperatures = np.array([[12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
                          23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12],
                         [13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
                          24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13],
                         [14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
                          25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14],
                         [15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
                          26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15],
                         [16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
                          27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16],
                         [17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
                          28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17],
                         [18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
                          29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18]])

Your task is to perform the following operations using indexing and slicing:

1. Extract the temperature readings for the first day.
2. Extract the temperature readings for the last day.
3. Extract the temperature readings for the first 12 hours of each day.
4. Extract the temperature readings for the last 6 hours of each day.
5. Extract the temperature readings for every other hour of the fourth day.
6. Modify the temperature readings for the first 3 hours of the fifth day to be 10 degrees higher.
7. Create a boolean mask to find all temperature readings above 25 degrees.


### [Solution](#)


1. Extract the temperature readings for the first day:

In [ ]:
first_day = temperatures[0, :]
print("Temperature readings for the first day:\n", first_day)

Temperature readings for the first day:
 [12 14 15 16 17 18 19 20 21 22 23 24 23 22 21 20 19 18 17 16 15 14 13 12]


2. Extract the temperature readings for the last day:

In [ ]:
last_day = temperatures[-1, :]
print("Temperature readings for the last day:\n", last_day)

Temperature readings for the last day:
 [18 20 21 22 23 24 25 26 27 28 29 30 29 28 27 26 25 24 23 22 21 20 19 18]


3. Extract the temperature readings for the first 12 hours of each day:

In [ ]:
first_12_hours = temperatures[:, :12]
print("Temperature readings for the first 12 hours of each day:\n", first_12_hours)

Temperature readings for the first 12 hours of each day:
 [[12 14 15 16 17 18 19 20 21 22 23 24]
 [13 15 16 17 18 19 20 21 22 23 24 25]
 [14 16 17 18 19 20 21 22 23 24 25 26]
 [15 17 18 19 20 21 22 23 24 25 26 27]
 [16 18 19 20 21 22 23 24 25 26 27 28]
 [17 19 20 21 22 23 24 25 26 27 28 29]
 [18 20 21 22 23 24 25 26 27 28 29 30]]


4. Extract the temperature readings for the last 6 hours of each day:

In [ ]:
last_6_hours = temperatures[:, -6:]
print("Temperature readings for the last 6 hours of each day:\n", last_6_hours)

Temperature readings for the last 6 hours of each day:
 [[17 16 15 14 13 12]
 [18 17 16 15 14 13]
 [19 18 17 16 15 14]
 [20 19 18 17 16 15]
 [21 20 19 18 17 16]
 [22 21 20 19 18 17]
 [23 22 21 20 19 18]]


5. Extract the temperature readings for every other hour of the fourth day:

In [ ]:
fourth_day_every_other_hour = temperatures[3, ::2]
print("Temperature readings for every other hour of the fourth day:\n", fourth_day_every_other_hour)

Temperature readings for every other hour of the fourth day:
 [15 18 20 22 24 26 26 24 22 20 18 16]


6. Modify the temperature readings for the first 3 hours of the fifth day to be 10 degrees higher:

In [ ]:
temperatures[4, :3] += 10
print("Modified temperature readings for the first 3 hours of the fifth day:\n", temperatures[4, :])

Modified temperature readings for the first 3 hours of the fifth day:
 [26 28 29 20 21 22 23 24 25 26 27 28 27 26 25 24 23 22 21 20 19 18 17 16]


7. Create a boolean mask to find all temperature readings above 25 degrees:

In [ ]:
above_25_mask = temperatures > 25
print("Boolean mask for temperature readings above 25 degrees:\n", above_25_mask)

Boolean mask for temperature readings above 25 degrees:
 [[False False False False False False False False False False False False
  False False False False False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False False False False False]
 [False False False False False False False False False False False  True
  False False False False False False False False False False False False]
 [False False False False False False False False False False  True  True
   True False False False False False False False False False False False]
 [ True  True  True False False False False False False  True  True  True
   True  True False False False False False False False False False False]
 [False False False False False False False False  True  True  True  True
   True  True  True False False False False False False False False False]
 [False False False False False False False  True

In [ ]:
above_25_temperatures = temperatures[above_25_mask]
print("Temperature readings above 25 degrees:\n", above_25_temperatures)

Temperature readings above 25 degrees:
 [26 26 27 26 26 28 29 26 27 28 27 26 26 27 28 29 28 27 26 26 27 28 29 30
 29 28 27 26]
