## [Practice Exercise: NumPy Data Types](#)

1. Create a NumPy array called `arr1` with the following values: [1, 2, 3, 4, 5]. Specify the data type as `int32`.

2. Create another NumPy array called `arr2` with the following values: [1.5, 2.5, 3.5, 4.5, 5.5]. Let NumPy infer the data type automatically.

3. Perform element-wise addition between `arr1` and `arr2` and store the result in a new array called `result`. Print the data type of `result`.

4. Create a structured array called `student` with the following fields: "name" (string of length 10), "age" (integer), and "grade" (float). Initialize the array with the following values:
   - ("John", 18, 85.5)
   - ("Alice", 20, 92.0)
   - ("Bob", 19, 88.7)

5. Access and print the "name" field of the `student` array.

6. Convert the `grade` field of the `student` array to an integer data type using explicit type casting.

7. Create a boolean array called `mask` that checks whether each element in `arr1` is greater than 3.

8. Use boolean indexing to extract the elements from `arr1` that correspond to the True values in `mask`.

9. Calculate the memory consumed by `arr1` and `arr2` in bytes.

10. Create a new array called `arr3` with the same shape as `arr1` but with a `float32` data type. Initialize it with zeros.


### [Solution](#)


In [ ]:
import numpy as np

In [ ]:
# 1. Create arr1 with int32 data type
arr1 = np.array([1, 2, 3, 4, 5], dtype=np.int32)
arr1

array([1, 2, 3, 4, 5], dtype=int32)

In [ ]:
# 2. Create arr2 and let NumPy infer the data type
arr2 = np.array([1.5, 2.5, 3.5, 4.5, 5.5])
arr2

array([1.5, 2.5, 3.5, 4.5, 5.5])

In [ ]:
# 3. Perform element-wise addition and print the data type of the result
result = arr1 + arr2
print("Data type of result:", result.dtype)

Data type of result: float64


In [ ]:
# 4. Create a structured array 'student'
student = np.array([("John", 18, 85.5), ("Alice", 20, 92.0), ("Bob", 19, 88.7)],
                   dtype=[("name", "S10"), ("age", "i4"), ("grade", "f4")])
student

array([(b'John', 18, 85.5), (b'Alice', 20, 92. ), (b'Bob', 19, 88.7)],
      dtype=[('name', 'S10'), ('age', '<i4'), ('grade', '<f4')])

In [ ]:
# 5. Access and print the "name" field of the 'student' array
print("Names:", student["name"])

Names: [b'John' b'Alice' b'Bob']


In [ ]:
# 6. Convert the "grade" field to an integer data type
student["grade"] = student["grade"].astype(int)

In [ ]:
# 7. Create a boolean array 'mask' based on a condition
mask = arr1 > 3
mask

array([False, False, False,  True,  True])

In [ ]:
# 8. Use boolean indexing to extract elements from arr1
filtered_arr1 = arr1[mask]
print("Filtered arr1:", filtered_arr1)
filtered_arr1

Filtered arr1: [4 5]


array([4, 5], dtype=int32)

In [ ]:
# 9. Calculate memory consumed by arr1 and arr2
print("Memory consumed by arr1:", arr1.nbytes, "bytes")
print("Memory consumed by arr2:", arr2.nbytes, "bytes")

Memory consumed by arr1: 20 bytes
Memory consumed by arr2: 40 bytes


In [ ]:
# 10. Create arr3 with the same shape as arr1 but with float32 data type
arr3 = np.zeros_like(arr1, dtype=np.float32)
arr3

array([0., 0., 0., 0., 0.], dtype=float32)