## [Practice Exercise: Broadcasting in NumPy](#)

In this exercise, you will apply your knowledge of broadcasting to perform various array operations using NumPy.

1. Create a 2D NumPy array `arr1` with shape `(3, 4)` filled with random integers between 1 and 10 (inclusive).

2. Create a 1D NumPy array `arr2` with shape `(4,)` filled with the values `[2, 4, 6, 8]`.

3. Perform element-wise addition between `arr1` and `arr2` using broadcasting and store the result in a new array `result1`.

4. Create a 2D NumPy array `arr3` with shape `(3, 1)` filled with the values `[10, 20, 30]`.

5. Perform element-wise multiplication between `arr1` and `arr3` using broadcasting and store the result in a new array `result2`.

6. Create a scalar value `scalar` with the value 5.

7. Subtract `scalar` from each element of `result1` using broadcasting and store the result in a new array `result3`.

8. Print the arrays `result1`, `result2`, and `result3`.


### [Solution](#)


Here's the solution to the practice exercise:


In [ ]:
import numpy as np

In [ ]:
# 1. Create arr1 with shape (3, 4) filled with random integers between 1 and 10
arr1 = np.random.randint(1, 11, size=(3, 4))
print("arr1:")
print(arr1)

arr1:
[[6 9 9 1]
 [9 8 5 4]
 [9 5 9 3]]


In [ ]:
# 2. Create arr2 with shape (4,) filled with the values [2, 4, 6, 8]
arr2 = np.array([2, 4, 6, 8])
print("\narr2:")
print(arr2)


arr2:
[2 4 6 8]


In [ ]:
# 3. Perform element-wise addition between arr1 and arr2 using broadcasting
result1 = arr1 + arr2
print("\nresult1:")
print(result1)


result1:
[[ 8 13 15  9]
 [11 12 11 12]
 [11  9 15 11]]


In [ ]:
# 4. Create arr3 with shape (3, 1) filled with the values [10, 20, 30]
arr3 = np.array([[10], [20], [30]])
print("\narr3:")
print(arr3)


arr3:
[[10]
 [20]
 [30]]


In [ ]:
# 5. Perform element-wise multiplication between arr1 and arr3 using broadcasting
result2 = arr1 * arr3
print("\nresult2:")
print(result2)


result2:
[[ 60  90  90  10]
 [180 160 100  80]
 [270 150 270  90]]


In [ ]:
# 6. Create a scalar value scalar with the value 5
scalar = 5

In [ ]:
# 7. Subtract scalar from each element of result1 using broadcasting
result3 = result1 - scalar
print("\nresult3:")
print(result3)


result3:
[[ 3  8 10  4]
 [ 6  7  6  7]
 [ 6  4 10  6]]


In this solution, we create the arrays `arr1`, `arr2`, and `arr3` according to the instructions. We then perform the specified broadcasting operations to obtain `result1`, `result2`, and `result3`. Finally, we print the resulting arrays.


This exercise helps you practice applying broadcasting rules to perform element-wise operations between arrays of different shapes and between arrays and scalars.