## [Practice Exercise: Analyzing Sales Data](#)

You are given two NumPy arrays `sales_2021` and `sales_2022` that contain the monthly sales data for a company over the past two years. Each array has shape `(3, 4)`, representing sales data for 3 products over 4 quarters.


In [ ]:
import numpy as np

sales_2021 = np.array([[100, 120, 140, 160],
                       [200, 220, 240, 260],
                       [300, 320, 340, 360]])

sales_2022 = np.array([[110, 130, 150, 170],
                       [210, 230, 250, 270],
                       [310, 330, 350, 370]])

Your task is to perform the following operations:

1. Combine the sales data for both years into a single array using vertical stacking.
2. Reshape the combined sales data into a 1D array.
3. Split the combined sales data into separate arrays for each product using horizontal splitting.
4. Create a new array that repeats the sales data for each year twice using tiling.
5. Calculate the total sales for each year using flattening and summation.


### [Solution](#)


1. Combine the sales data for both years into a single array using vertical stacking:

In [ ]:
combined_sales = np.vstack((sales_2021, sales_2022))
combined_sales

array([[100, 120, 140, 160],
       [200, 220, 240, 260],
       [300, 320, 340, 360],
       [110, 130, 150, 170],
       [210, 230, 250, 270],
       [310, 330, 350, 370]])

2. Reshape the combined sales data into a 1D array:

In [ ]:
flattened_sales = np.ravel(combined_sales)
flattened_sales

array([100, 120, 140, 160, 200, 220, 240, 260, 300, 320, 340, 360, 110,
       130, 150, 170, 210, 230, 250, 270, 310, 330, 350, 370])

3. Split the combined sales data into separate arrays for each product using horizontal splitting:

In [ ]:
combined_sales

array([[100, 120, 140, 160],
       [200, 220, 240, 260],
       [300, 320, 340, 360],
       [110, 130, 150, 170],
       [210, 230, 250, 270],
       [310, 330, 350, 370]])

In [ ]:
product_sales = np.vsplit(combined_sales, 3)
print("Sales data for each product:")
for i, product in enumerate(product_sales, start=1):
    print(f"Product {i}:\n", product)

Sales data for each product:
Product 1:
 [[100 120 140 160]
 [200 220 240 260]]
Product 2:
 [[300 320 340 360]
 [110 130 150 170]]
Product 3:
 [[210 230 250 270]
 [310 330 350 370]]


4. Create a new array that repeats the sales data for each year twice using tiling:

In [ ]:
tiled_sales = np.tile(combined_sales, (2, 1))
print("Tiled sales data:\n", tiled_sales)

Tiled sales data:
 [[100 120 140 160]
 [200 220 240 260]
 [300 320 340 360]
 [110 130 150 170]
 [210 230 250 270]
 [310 330 350 370]
 [100 120 140 160]
 [200 220 240 260]
 [300 320 340 360]
 [110 130 150 170]
 [210 230 250 270]
 [310 330 350 370]]


5. Calculate the total sales for each year using flattening and summation:

In [ ]:
total_sales_2021 = np.sum(sales_2021)
total_sales_2022 = np.sum(sales_2022)
print("Total sales for 2021:", total_sales_2021)
print("Total sales for 2022:", total_sales_2022)

Total sales for 2021: 2760
Total sales for 2022: 2880


In this exercise, we used various NumPy array manipulation functions to analyze the sales data:

1. `np.vstack()` was used to vertically stack the sales data for both years into a single array.
2. `np.ravel()` was used to reshape the combined sales data into a 1D array.
3. `np.hsplit()` was used to split the combined sales data horizontally into separate arrays for each product.
4. `np.tile()` was used to create a new array that repeats the sales data for each year twice.
5. `np.sum()` was used to calculate the total sales for each year after flattening the arrays.


This exercise demonstrates how NumPy's array manipulation functions can be applied to real-world data analysis tasks, such as combining, reshaping, splitting, and aggregating sales data.


Feel free to modify the sales data arrays and experiment with different operations and functions to further practice and reinforce your understanding of NumPy array manipulation techniques.