## [Practice Exercise: Analyzing Student Grades](#)

You are given a NumPy array `grades` that contains the grades of a group of students in a course. Your task is to perform the following operations:

1. Sort the grades in ascending order.
2. Find the top 5 grades using array slicing.
3. Determine the number of students who passed the course (grade >= 60).
4. Identify the students who scored below the mean grade.
5. Find the unique grades in the array.


In [ ]:
import numpy as np

grades = np.array([85, 72, 90, 68, 77, 82, 92, 60, 55, 75, 88, 80, 95, 78, 65])

### [Solution](#)


1. Sort the grades in ascending order:

In [ ]:
sorted_grades = np.sort(grades)
sorted_grades

array([55, 60, 65, 68, 72, 75, 77, 78, 80, 82, 85, 88, 90, 92, 95])

2. Find the top 5 grades using array slicing:

In [ ]:
top_5_grades = sorted_grades[-5:]
top_5_grades

array([85, 88, 90, 92, 95])

3. Determine the number of students who passed the course (grade >= 60):

In [ ]:
passed_students = np.sum(grades >= 60)
passed_students

14

4. Identify the students who scored below the mean grade:

In [ ]:
mean_grade = np.mean(grades)
mean_grade

77.46666666666667

In [ ]:
below_mean_mask = grades < mean_grade
below_mean_mask

array([False,  True, False,  True,  True, False, False,  True,  True,
        True, False, False, False, False,  True])

In [ ]:
below_mean_grades = grades[below_mean_mask]
below_mean_grades

array([72, 68, 77, 60, 55, 75, 65])

5. Find the unique grades in the array:

In [ ]:
unique_grades = np.unique(grades)
unique_grades

array([55, 60, 65, 68, 72, 75, 77, 78, 80, 82, 85, 88, 90, 92, 95])

In this exercise, we used various NumPy sorting and searching functions to analyze the student grades:

1. `np.sort()` was used to sort the grades in ascending order.
2. Array slicing `sorted_grades[-5:]` was used to extract the top 5 grades.
3. `np.sum(grades >= 60)` counted the number of students who passed the course by summing the boolean mask.
4. Boolean indexing `grades[below_mean_mask]` was used to identify the grades below the mean grade.
5. `np.unique()` was used to find the unique grades in the array.


This exercise demonstrates how NumPy's sorting and searching functions can be applied to real-world data analysis tasks, such as analyzing student grades and deriving meaningful insights from the data.


Feel free to modify the `grades` array and experiment with different operations and functions to further practice and reinforce your understanding of NumPy sorting and searching techniques.