## [Exercise: Saving and Loading NumPy Objects](#)

In this exercise, you will practice saving and loading NumPy objects using different formats, including CSV and text files.

1. Create a NumPy array called `data` with the following values:
   ```
   [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
   ```

2. Save the `data` array to a file named `array_data.npy` using NumPy's native binary format.

3. Load the saved array from `array_data.npy` and assign it to a variable named `loaded_data`.

4. Create a NumPy array called `matrix` with the following values:
   ```
   [[1.5, 2.7, 3.2],
    [4.1, 5.9, 6.8],
    [7.3, 8.6, 9.4]]
   ```

5. Save the `matrix` array to a file named `matrix_data.txt` in plain text format, with each element separated by a comma.

6. Load the saved matrix from `matrix_data.txt` and assign it to a variable named `loaded_matrix`.

7. Create a dictionary called `data_dict` with the following key-value pairs:
   - 'array1': `data` (from step 1)
   - 'array2': `matrix` (from step 4)

8. Save the `data_dict` dictionary to a file named `data_archive.npz` using NumPy's compressed format.

9. Load the saved dictionary from `data_archive.npz` and assign it to a variable named `loaded_dict`.

10. Create a NumPy array called `csv_data` with the following values:
    ```
    [['Name', 'Age', 'City'],
     ['Alice', 25, 'New York'],
     ['Bob', 30, 'London'],
     ['Charlie', 35, 'Paris']]
    ```

11. Save the `csv_data` array to a file named `data.csv` in CSV format, with each element separated by a comma and including a header row.

12. Load the saved CSV data from `data.csv` and assign it to a variable named `loaded_csv_data`.

13. Create a NumPy array called `txt_data` with the following values:
    ```
    [[1.2, 3.4, 5.6],
     [7.8, 9.0, 10.2]]
    ```

14. Save the `txt_data` array to a file named `data.txt` in plain text format, with each element separated by a space.

15. Load the saved text data from `data.txt` and assign it to a variable named `loaded_txt_data`.

16. Print the shapes and contents of `loaded_data`, `loaded_matrix`, `loaded_dict['array1']`, `loaded_dict['array2']`, `loaded_csv_data`, and `loaded_txt_data`.


## [Solution](#)


In [ ]:
import numpy as np

In [ ]:
# Step 1
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])


In [ ]:
# Step 2
np.save('array_data.npy', data)


In [ ]:
# Step 3
loaded_data = np.load('array_data.npy')


In [ ]:
# Step 4
matrix = np.array([[1.5, 2.7, 3.2],
                   [4.1, 5.9, 6.8],
                   [7.3, 8.6, 9.4]])


In [ ]:
# Step 5
np.savetxt('matrix_data.txt', matrix, delimiter=',')


In [ ]:
# Step 6
loaded_matrix = np.loadtxt('matrix_data.txt', delimiter=',')


In [ ]:
# Step 7
data_dict = {
    'array1': data,
    'array2': matrix
}


In [ ]:
# Step 8
np.savez_compressed('data_archive.npz', **data_dict)


In [ ]:
# Step 9
loaded_dict = np.load('data_archive.npz')


In [ ]:
# Step 10
csv_data = np.array([['Name', 'Age', 'City'],
                     ['Alice', 25, 'New York'],
                     ['Bob', 30, 'London'],
                     ['Charlie', 35, 'Paris']])


In [ ]:
# Step 11
np.savetxt('data.csv', csv_data, delimiter=',', fmt='%s')


In [ ]:
# Step 12
loaded_csv_data = np.genfromtxt('data.csv', delimiter=',', dtype=str)


In [ ]:
# Step 13
txt_data = np.array([[1.2, 3.4, 5.6],
                     [7.8, 9.0, 10.2]])


In [ ]:
# Step 14
np.savetxt('data.txt', txt_data)


In [ ]:
# Step 15
loaded_txt_data = np.loadtxt('data.txt')


In [ ]:
# Step 16
print("Shape of loaded_data:", loaded_data.shape)
print("Content of loaded_data:\n", loaded_data)


Shape of loaded_data: (3, 3)
Content of loaded_data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print("\nShape of loaded_matrix:", loaded_matrix.shape)
print("Content of loaded_matrix:\n", loaded_matrix)



Shape of loaded_matrix: (3, 3)
Content of loaded_matrix:
 [[1.5 2.7 3.2]
 [4.1 5.9 6.8]
 [7.3 8.6 9.4]]


In [ ]:
print("\nShape of loaded_dict['array1']:", loaded_dict['array1'].shape)
print("Content of loaded_dict['array1']:\n", loaded_dict['array1'])



Shape of loaded_dict['array1']: (3, 3)
Content of loaded_dict['array1']:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print("\nShape of loaded_dict['array2']:", loaded_dict['array2'].shape)
print("Content of loaded_dict['array2']:\n", loaded_dict['array2'])



Shape of loaded_dict['array2']: (3, 3)
Content of loaded_dict['array2']:
 [[1.5 2.7 3.2]
 [4.1 5.9 6.8]
 [7.3 8.6 9.4]]


In [ ]:
print("\nShape of loaded_csv_data:", loaded_csv_data.shape)
print("Content of loaded_csv_data:\n", loaded_csv_data)



Shape of loaded_csv_data: (4, 3)
Content of loaded_csv_data:
 [['Name' 'Age' 'City']
 ['Alice' '25' 'New York']
 ['Bob' '30' 'London']
 ['Charlie' '35' 'Paris']]


In [ ]:
print("\nShape of loaded_txt_data:", loaded_txt_data.shape)
print("Content of loaded_txt_data:\n", loaded_txt_data)


Shape of loaded_txt_data: (2, 3)
Content of loaded_txt_data:
 [[ 1.2  3.4  5.6]
 [ 7.8  9.  10.2]]


This updated exercise includes additional steps for creating and saving data to CSV and text files. The CSV file includes a header row, and the data is saved using `np.savetxt()` with the `fmt='%s'` parameter to handle string data. The text file is saved using `np.savetxt()` with the default space delimiter.


The loaded data from the CSV and text files are assigned to `loaded_csv_data` and `loaded_txt_data`, respectively. Finally, the shapes and contents of all the loaded data are printed for verification.


This exercise covers a comprehensive set of scenarios for saving and loading NumPy objects using various formats, including NumPy's native binary format, compressed format, CSV files, and plain text files.