# [Mathematical Operations with NumPy](#)

NumPy is a powerful library for performing mathematical operations on arrays and matrices. It provides a wide range of mathematical functions and operators that can be applied element-wise on arrays, making it easy to perform complex calculations efficiently.


One of the key advantages of using NumPy for mathematical operations is its ability to perform **vectorized operations**. Vectorization allows you to apply operations on entire arrays without the need for explicit loops, resulting in faster and more concise code.


NumPy's mathematical operations can be broadly categorized into the following areas:

1. **Element-wise arithmetic operations**: These include basic operations like addition, subtraction, multiplication, and division, which are performed element-wise on arrays.

2. **Mathematical functions**: NumPy provides a comprehensive set of mathematical functions, such as trigonometric functions (e.g., `sin`, `cos`, `tan`), exponential and logarithmic functions (e.g., `exp`, `log`), and rounding functions (e.g., `floor`, `ceil`, `round`).

3. **Aggregation functions**: These functions operate on arrays and return a single value, such as `sum`, `mean`, `min`, `max`, `std` (standard deviation), and `var` (variance).

4. **Matrix operations**: NumPy provides functions for matrix operations, such as matrix multiplication (`dot`), matrix transposition (`transpose`), and matrix inversion (`linalg.inv`).


In the following sections, we will explore each of these categories in more detail and provide examples of how to use NumPy's mathematical operations effectively.


By leveraging NumPy's mathematical operations, you can perform complex calculations on large arrays and matrices efficiently, making it an essential tool for scientific computing, data analysis, and numerical simulations.


Let's dive into the world of mathematical operations with NumPy!

## [Element-wise Arithmetic Operations](#)

NumPy provides basic arithmetic operations that can be performed element-wise on arrays. These operations include addition, subtraction, multiplication, and division. Let's explore each of these operations in detail.


### [Addition](#)


Addition of two arrays in NumPy is performed using the `+` operator or the `np.add()` function. The arrays must have the same shape or be broadcastable to a common shape.


Example:

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [3]:
# Using the + operator
a + b

array([5, 7, 9])

In [4]:
# Using the np.add() function
np.add(a, b)

array([5, 7, 9])

### [Subtraction](#)


Subtraction of two arrays in NumPy is performed using the `-` operator or the `np.subtract()` function. The arrays must have the same shape or be broadcastable to a common shape.


Example:

In [5]:
a = np.array([5, 7, 9])
b = np.array([2, 3, 4])

In [6]:
# Using the - operator
a - b

array([3, 4, 5])

In [7]:
# Using the np.subtract() function
np.subtract(a, b)

array([3, 4, 5])

### [Multiplication](#)


Multiplication of two arrays in NumPy is performed using the `*` operator or the `np.multiply()` function. The arrays must have the same shape or be broadcastable to a common shape.


Example:

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [9]:
# Using the * operator
a * b

array([ 4, 10, 18])

In [10]:
# Using the np.multiply() function
np.multiply(a, b)

array([ 4, 10, 18])

### [Division](#)


Division of two arrays in NumPy is performed using the `/` operator or the `np.divide()` function. The arrays must have the same shape or be broadcastable to a common shape.


Example:

In [11]:
a = np.array([10, 20, 30])
b = np.array([2, 5, 10])

In [12]:
# Using the / operator
a / b

array([5., 4., 3.])

In [13]:
# Using the np.divide() function
np.divide(a, b)

array([5., 4., 3.])

It's important to note that when performing division, if the arrays contain integer values, the result will be truncated to integers unless at least one of the arrays is of a floating-point type.


These element-wise arithmetic operations are fundamental building blocks for more complex mathematical computations in NumPy. They allow you to perform calculations on arrays efficiently without the need for explicit loops.


## [Basic Mathematical Functions](#)

NumPy provides a wide range of mathematical functions that can be applied element-wise on arrays. These functions include trigonometric functions, exponential and logarithmic functions, and rounding functions. Let's explore each category in detail.


### [Trigonometric Functions](#)


NumPy offers a set of trigonometric functions that can be applied to arrays. These functions operate element-wise and return an array of the same shape as the input array.


Example:

In [14]:
a = np.array([0, np.pi/4, np.pi/2])

In [15]:
np.sin(a)

array([0.        , 0.70710678, 1.        ])

In [16]:
np.cos(a)

array([1.00000000e+00, 7.07106781e-01, 6.12323400e-17])

In [17]:
np.tan(a)

array([0.00000000e+00, 1.00000000e+00, 1.63312394e+16])

The `np.sin()`, `np.cos()`, and `np.tan()` functions compute the sine, cosine, and tangent of each element in the input array, respectively.


NumPy also provides inverse trigonometric functions, such as `np.arcsin()`, `np.arccos()`, and `np.arctan()`, which compute the inverse sine, inverse cosine, and inverse tangent of each element in the array.


### [Exponential and Logarithmic Functions](#)


NumPy provides exponential and logarithmic functions that can be applied element-wise on arrays.


Example:

In [18]:
a = np.array([1, 2, 3])

In [19]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [20]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [21]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125])

The `np.exp()` function computes the exponential of each element in the input array, i.e., $e^x$ for each element $x$.


The `np.log()` function computes the natural logarithm (base $e$) of each element in the input array, while `np.log10()` computes the logarithm base 10 of each element.


NumPy also provides other logarithmic functions, such as `np.log2()` for logarithm base 2 and `np.log1p()` for computing $\log(1 + x)$ more accurately for small values of $x$.


### [Rounding Functions](#)


NumPy offers various rounding functions that can be used to round array elements to specific precision or to the nearest integer.


Example:

In [22]:
a = np.array([1.23, 4.56, 7.89])

In [23]:
np.round(a)

array([1., 5., 8.])

In [24]:
np.ceil(a)

array([2., 5., 8.])

In [25]:
np.floor(a)

array([1., 4., 7.])

The `np.round()` function rounds each element in the input array to the nearest integer. It can also take an optional decimal argument to specify the number of decimal places to round to.


The `np.ceil()` function rounds each element in the input array to the nearest integer greater than or equal to the element (ceiling function).


The `np.floor()` function rounds each element in the input array to the nearest integer less than or equal to the element (floor function).


These are just a few examples of the basic mathematical functions provided by NumPy. NumPy offers many more functions for various mathematical operations, such as hyperbolic functions (`np.sinh()`, `np.cosh()`, `np.tanh()`), arithmetic functions (`np.add()`, `np.subtract()`, `np.multiply()`, `np.divide()`), and more.


By utilizing these mathematical functions, you can perform complex calculations on arrays efficiently and with concise code.


## [Aggregation Functions](#)

NumPy provides a set of aggregation functions that allow you to perform operations across array axes and compute summary statistics. These functions reduce the dimensions of an array and return a single value or a reduced array. Let's explore some commonly used aggregation functions.


### [Sum](#)


The `np.sum()` function computes the sum of elements in an array. It can be used to calculate the sum along a specific axis or the entire array.


Example:

In [26]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [27]:
np.sum(a)

21

In [28]:
np.sum(a, axis=0)

array([5, 7, 9])

In [29]:
np.sum(a, axis=1)

array([ 6, 15])

When used without the `axis` parameter, `np.sum()` computes the sum of all elements in the array.


<img src="../images/numpy-arrays.png" width="800">

The `axis` parameter specifies the axis along which the sum is computed. `axis=0` computes the sum along the rows (resulting in a sum for each column), while `axis=1` computes the sum along the columns (resulting in a sum for each row).


### [Mean](#)


The `np.mean()` function computes the arithmetic mean of elements in an array. It can be used to calculate the mean along a specific axis or the entire array.


Example:

In [30]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [31]:
np.mean(a)

3.5

In [32]:
np.mean(a, axis=0)

array([2.5, 3.5, 4.5])

In [33]:
np.mean(a, axis=1)

array([2., 5.])

Similar to `np.sum()`, when used without the `axis` parameter, `np.mean()` computes the mean of all elements in the array.


The `axis` parameter specifies the axis along which the mean is computed. `axis=0` computes the mean along the rows (resulting in a mean for each column), while `axis=1` computes the mean along the columns (resulting in a mean for each row).


### [Minimum and Maximum](#)


The `np.min()` and `np.max()` functions compute the minimum and maximum values of elements in an array, respectively. They can be used to find the minimum or maximum along a specific axis or the entire array.


Example:

In [34]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [35]:
np.min(a)

1

In [36]:
np.max(a)

6

In [37]:
np.min(a, axis=0)

array([1, 2, 3])

In [38]:
np.max(a, axis=1)

array([3, 6])

When used without the `axis` parameter, `np.min()` and `np.max()` compute the minimum and maximum values of all elements in the array, respectively.


The `axis` parameter specifies the axis along which the minimum or maximum is computed. `axis=0` computes the minimum or maximum along the rows (resulting in a minimum or maximum for each column), while `axis=1` computes the minimum or maximum along the columns (resulting in a minimum or maximum for each row).


### [Standard Deviation and Variance](#)


The `np.std()` and `np.var()` functions compute the standard deviation and variance of elements in an array, respectively. They can be used to calculate these statistics along a specific axis or the entire array.


Example:

In [39]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [40]:
np.std(a)

1.707825127659933

In [41]:
np.var(a)

2.9166666666666665

In [42]:
np.std(a, axis=0)

array([1.5, 1.5, 1.5])

In [43]:
np.var(a, axis=1)

array([0.66666667, 0.66666667])

When used without the `axis` parameter, `np.std()` and `np.var()` compute the standard deviation and variance of all elements in the array, respectively.


The `axis` parameter specifies the axis along which the standard deviation or variance is computed. `axis=0` computes the standard deviation or variance along the rows (resulting in a value for each column), while `axis=1` computes the standard deviation or variance along the columns (resulting in a value for each row).


These aggregation functions are just a few examples of the many functions available in NumPy for computing summary statistics and performing operations across array axes. Other useful functions include `np.median()` for computing the median, `np.percentile()` for computing percentiles, and `np.prod()` for computing the product of elements.


Aggregation functions are powerful tools for analyzing and summarizing data in arrays, allowing you to extract meaningful insights efficiently.


## [Broadcasting in Mathematical Operations](#)

Broadcasting is a powerful feature in NumPy that allows arithmetic operations to be performed on arrays with different shapes. It enables you to perform operations between arrays of different sizes without the need for explicit broadcasting or reshaping.


In the previous lecture on broadcasting, we covered the basic concepts and rules of broadcasting. To recap, broadcasting allows NumPy to perform element-wise operations on arrays with different shapes by virtually expanding the smaller array to match the shape of the larger array.


When performing mathematical operations on arrays, broadcasting comes into play when the arrays have different shapes. NumPy follows a set of broadcasting rules to determine if the arrays are compatible for broadcasting:

1. If the arrays have different numbers of dimensions, the shape of the array with fewer dimensions is padded with ones on its left side.
2. If the shape of the arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.


Let's consider an example to illustrate broadcasting in mathematical operations:


In [44]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

In [45]:
a + b

array([[11, 22, 33],
       [14, 25, 36]])

In this example, array `a` has a shape of `(2, 3)`, while array `b` has a shape of `(3,)`. According to the broadcasting rules, array `b` is stretched to match the shape of array `a` along the second dimension. The resulting broadcasted shape is `(2, 3)`, and the element-wise addition is performed.


Broadcasting allows you to perform various mathematical operations between arrays of different shapes efficiently. Here are a few more examples:


In [46]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[10], [20]])

In [47]:
a * b

array([[ 10,  20,  30],
       [ 80, 100, 120]])

In [48]:
a / b

array([[0.1 , 0.2 , 0.3 ],
       [0.2 , 0.25, 0.3 ]])

In [49]:
a ** b

array([[               1,             1024,            59049],
       [   1099511627776,   95367431640625, 3656158440062976]])

In these examples, broadcasting is used to perform element-wise multiplication, division, and exponentiation between arrays `a` and `b`. Array `b` is broadcasted along the second dimension to match the shape of array `a`.


Broadcasting is not limited to arithmetic operations; it can be used with other mathematical functions as well. For example:


In [50]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([np.pi])

In [51]:
np.sin(a + b)

array([[-0.84147098, -0.90929743, -0.14112001],
       [ 0.7568025 ,  0.95892427,  0.2794155 ]])

In this example, the scalar value `np.pi` is broadcasted to match the shape of array `a`, and the element-wise sine function is applied to the result of the addition.


Broadcasting is a fundamental concept in NumPy that simplifies mathematical operations between arrays of different shapes. It allows you to write concise and efficient code without the need for explicit loops or reshaping operations.


However, it's important to be cautious when using broadcasting, as it can sometimes lead to unexpected results if the shapes of the arrays are not compatible. It's always a good practice to ensure that the arrays have compatible shapes before performing broadcasting operations.


## [Matrix Operations](#)

NumPy provides a comprehensive set of functions for performing matrix operations, which are essential in linear algebra, machine learning, and many other fields. In this section, we will explore some of the most commonly used matrix operations in NumPy.


### [Matrix Multiplication](#)


Matrix multiplication is a fundamental operation in linear algebra. NumPy provides the `np.dot()` function for performing matrix multiplication between two arrays.


<img src="../images/matrix-multiply.png" width="800">

<img src="../images/matrix-multiply-numbers.png" width="800">

Example:

In [52]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

In [53]:
np.dot(A, B)

array([[ 58,  64],
       [139, 154]])

In this example, matrix `A` has a shape of `(2, 3)`, and matrix `B` has a shape of `(3, 2)`. The `np.dot()` function computes the matrix product of `A` and `B`, resulting in a matrix of shape `(2, 2)`.


Matrix multiplication is only defined when the number of columns in the first matrix matches the number of rows in the second matrix. The resulting matrix has the same number of rows as the first matrix and the same number of columns as the second matrix.


NumPy also provides the `@` operator as a shorthand for matrix multiplication:


In [54]:
A @ B

array([[ 58,  64],
       [139, 154]])

This is equivalent to calling `np.dot(A, B)`.


### [Matrix Transposition](#)


Matrix transposition is the operation of interchanging the rows and columns of a matrix. In NumPy, you can transpose a matrix using the `np.transpose()` function or the `T` attribute of an array.


Example:

In [55]:
A = np.array([[1, 2, 3], [4, 5, 6]])

In [56]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [57]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

Both `np.transpose(A)` and `A.T` return the transposed matrix, where the rows of `A` become the columns, and the columns of `A` become the rows.


Transposing a matrix is a common operation in many mathematical computations and is often used to prepare matrices for further operations.


### [Matrix Inversion](#)


Matrix inversion is the process of finding the inverse of a square matrix. The inverse of a matrix `A` is denoted as `A^(-1)`, and when multiplied with the original matrix, it results in the identity matrix.


NumPy provides the `np.linalg.inv()` function for computing the inverse of a matrix.


Example:

In [58]:
A = np.array([[1, 2], [3, 4]])

In [59]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In this example, `np.linalg.inv(A)` computes the inverse of matrix `A`. The resulting matrix `A^(-1)` satisfies the property `A * A^(-1) = I`, where `I` is the identity matrix.


It's important to note that not all matrices have an inverse. A matrix is invertible only if it is square and has a non-zero determinant. If a matrix is not invertible (singular), attempting to compute its inverse will raise a `LinAlgError`.


NumPy also provides other matrix operations in the `np.linalg` module, such as `np.linalg.det()` for computing the determinant of a matrix, `np.linalg.solve()` for solving a system of linear equations, and `np.linalg.eig()` for computing the eigenvalues and eigenvectors of a matrix.


Matrix operations are fundamental in many scientific and engineering applications, and NumPy provides an efficient and convenient way to perform these operations on arrays.


## [NumPy's Random Number Generation](#)

NumPy provides a powerful random number generation module called `numpy.random`. This module allows you to generate various types of random numbers and distributions, which are useful for simulations, statistical sampling, machine learning, and more. Let's explore some of the commonly used functions for random number generation in NumPy.


### [Generating Random Numbers](#)


NumPy's `random` module provides functions to generate random numbers from different distributions. Here are a few examples:


In [60]:
# Generate a random float between 0 and 1
np.random.rand()

0.5881506594609676

In [61]:
# Generate a random integer between 0 and 9
np.random.randint(0, 10)

9

In [62]:
# Generate a random float from a normal distribution with mean 0 and standard deviation 1
np.random.randn()

1.2295483672153933

In [63]:
# Generate a random sample from a standard normal distribution
np.random.normal()

-0.6240993284639127

In [64]:
# Generate a random sample from a uniform distribution between 0 and 1
np.random.uniform()

0.11793910674356367

These functions allow you to generate random numbers with different properties and distributions. You can also specify the size of the output array to generate multiple random numbers at once:


In [65]:
# Generate a 1D array of 5 random floats between 0 and 1
np.random.rand(5)

array([0.46401232, 0.08144409, 0.31155317, 0.48572167, 0.40015427])

In [66]:
# Generate a 2D array of 3x3 random integers between 0 and 9
np.random.randint(0, 10, (3, 3))

array([[3, 9, 9],
       [8, 9, 8],
       [3, 3, 8]])

### [Seeding the Random Number Generator](#)


NumPy's random number generator uses a seed value to initialize its internal state. By default, the seed is set randomly, which means that each time you run your code, you will get different random numbers. However, you can set a specific seed value using `np.random.seed()` to generate reproducible random numbers.


In [67]:
# Set a seed value
np.random.seed(42)

In [68]:
# Generate random numbers
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

By setting the seed to a fixed value (e.g., 42), you ensure that the same sequence of random numbers is generated every time you run the code with the same seed. This is useful for reproducibility and debugging purposes.


### [Generating Random Arrays](#)


NumPy's `random` module also provides functions to generate random arrays with specific properties. Here are a few examples:


In [69]:
# Generate a random permutation of an array
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
arr

array([4, 2, 3, 1, 5])

In [70]:
# Generate a random sample of elements from an array
np.random.choice(arr, size=3)

array([3, 3, 3])

In [71]:
# Generate a random integer array with values between 0 and 9
np.random.randint(0, 10, size=(3, 3))

array([[7, 4, 3],
       [7, 7, 2],
       [5, 4, 1]])

These functions allow you to generate random arrays by shuffling existing arrays, sampling elements from an array, or generating arrays with random integer values.


### [Generating Random Samples from Distributions](#)


NumPy's `random` module provides functions to generate random samples from various probability distributions. Here are a few examples:


In [72]:
# Generate a random sample from a normal distribution
np.random.normal(loc=0, scale=1, size=(2, 2))

array([[0.23309524, 0.11799461],
       [1.46237812, 1.53871497]])

In [73]:
# Generate a random sample from a uniform distribution
np.random.uniform(low=0, high=1, size=(2, 2))

array([[0.00706631, 0.02306243],
       [0.52477466, 0.39986097]])

In [74]:
# Generate a random sample from a binomial distribution
np.random.binomial(n=10, p=0.5, size=(2, 2))

array([[2, 8],
       [4, 3]])

In [75]:
# Generate a random sample from a Poisson distribution
np.random.poisson(lam=2, size=(2, 2))

array([[3, 3],
       [3, 1]])

These functions allow you to generate random samples from distributions such as normal, uniform, binomial, Poisson, and many others. You can specify the parameters of the distribution and the size of the output array.


NumPy's random number generation capabilities are extensive and versatile. They provide a wide range of functions to generate random numbers, arrays, and samples from various distributions. These functions are essential for simulations, statistical modeling, data analysis, and machine learning tasks.


## [Comparison and Logical Operations](#)

NumPy provides a set of functions and operators for performing element-wise comparisons and logical operations on arrays. These operations allow you to compare arrays element-wise, test for certain conditions, and combine logical expressions. Let's explore the different types of comparison and logical operations in NumPy.


### [Comparison Operators](#)


NumPy supports the following comparison operators for element-wise comparisons:

- `==`: Equal to
- `!=`: Not equal to
- `<`: Less than
- `>`: Greater than
- `<=`: Less than or equal to
- `>=`: Greater than or equal to


These operators compare two arrays element-wise and return a boolean array of the same shape, indicating the result of the comparison for each corresponding element.


Example:

In [76]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

In [77]:
a == b

array([False, False,  True, False, False])

In [78]:
a != b

array([ True,  True, False,  True,  True])

In [79]:
a < b

array([ True,  True, False, False, False])

In [80]:
a > b

array([False, False, False,  True,  True])

In [81]:
a <= b

array([ True,  True,  True, False, False])

In [82]:
a >= b

array([False, False,  True,  True,  True])

The resulting boolean arrays contain `True` where the condition is satisfied and `False` otherwise.


### [Logical Operators](#)


NumPy provides the following logical operators for element-wise logical operations:

- `&`: Logical AND
- `|`: Logical OR
- `~`: Logical NOT


These operators perform element-wise logical operations on boolean arrays and return a boolean array of the same shape.


Example:

In [83]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

In [84]:
a & b

array([ True, False, False, False])

In [85]:
a | b

array([ True,  True,  True, False])

In [86]:
~a

array([False,  True, False,  True])

The logical AND operator (`&`) returns `True` where both arrays have `True` elements, the logical OR operator (`|`) returns `True` where either array has a `True` element, and the logical NOT operator (`~`) inverts the boolean values.


### [Comparison Functions](#)


NumPy provides several functions for performing element-wise comparisons:

- `np.equal(a, b)`: Returns `True` where `a` and `b` are equal.
- `np.not_equal(a, b)`: Returns `True` where `a` and `b` are not equal.
- `np.less(a, b)`: Returns `True` where `a` is less than `b`.
- `np.greater(a, b)`: Returns `True` where `a` is greater than `b`.
- `np.less_equal(a, b)`: Returns `True` where `a` is less than or equal to `b`.
- `np.greater_equal(a, b)`: Returns `True` where `a` is greater than or equal to `b`.


These functions are equivalent to the comparison operators but provide a more readable and expressive way to perform element-wise comparisons.


Example:

In [87]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

In [88]:
np.equal(a, b)

array([False, False,  True, False, False])

In [89]:
np.not_equal(a, b)

array([ True,  True, False,  True,  True])

In [90]:
np.less(a, b)

array([ True,  True, False, False, False])

In [91]:
np.greater(a, b)

array([False, False, False,  True,  True])

In [92]:
np.less_equal(a, b)

array([ True,  True,  True, False, False])

In [93]:
np.greater_equal(a, b)


array([False, False,  True,  True,  True])

### [Logical Functions](#)


NumPy provides several functions for performing element-wise logical operations:

- `np.logical_and(a, b)`: Returns `True` where both `a` and `b` are `True`.
- `np.logical_or(a, b)`: Returns `True` where either `a` or `b` is `True`.
- `np.logical_not(a)`: Returns `True` where `a` is `False`.
- `np.logical_xor(a, b)`: Returns `True` where either `a` or `b` is `True`, but not both.


These functions are equivalent to the logical operators but provide a more readable and expressive way to perform element-wise logical operations.


Example:

In [94]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

In [95]:
np.logical_and(a, b)

array([ True, False, False, False])

In [96]:
np.logical_or(a, b)

array([ True,  True,  True, False])

In [97]:
np.logical_not(a)

array([False,  True, False,  True])

In [98]:
np.logical_xor(a, b)

array([False,  True,  True, False])

Comparison and logical operations are essential for conditional statements, data filtering, and boolean indexing in NumPy. They allow you to select elements based on certain conditions, create masks for indexing, and perform logical operations on arrays.


## [Conclusion and Further Resources](#)

In this lecture, we explored the various mathematical operations provided by NumPy. We started with element-wise arithmetic operations, which allow us to perform basic math operations on arrays efficiently. We then delved into the rich set of mathematical functions offered by NumPy, including trigonometric, exponential, logarithmic, and rounding functions.


We also learned about aggregation functions, which enable us to compute summary statistics and perform operations across array axes. Broadcasting, a powerful feature of NumPy, was discussed, allowing us to perform operations on arrays with different shapes seamlessly.


Matrix operations, such as matrix multiplication, transposition, and inversion, were introduced, highlighting NumPy's capabilities for linear algebra computations. We explored random number generation using NumPy's `random` module, which provides functions for generating random numbers, arrays, and samples from various distributions.


Comparison and logical operations were covered, enabling element-wise comparisons and logical operations on arrays. Lastly, we saw how mathematical operations can be applied to boolean arrays, facilitating conditional computations and data manipulation.


NumPy's mathematical operations form the foundation for scientific computing and data analysis in Python. By leveraging these operations, you can perform complex calculations, manipulate data, and solve mathematical problems efficiently.


Some popular tutorials enhance your understanding and proficiency in using NumPy's mathematical operations include:
   - [NumPy Quickstart Tutorial](https://numpy.org/doc/stable/user/quickstart.html)
   - [NumPy Tutorial on W3Schools](https://www.w3schools.com/python/numpy/default.asp)
   - [NumPy Tutorial on Real Python](https://realpython.com/numpy-tutorial/)


By exploring these resources and engaging in hands-on practice, you can deepen your knowledge of NumPy's mathematical operations and harness their power for various computational tasks.


Remember, NumPy is a fundamental library in the scientific Python ecosystem, and mastering its mathematical operations will open up a wide range of possibilities for data analysis, scientific computing, and machine learning applications.