# [Sorting and Searching in NumPy](#)

Sorting and searching are fundamental operations in data processing and analysis. They play a crucial role in various domains, including:

- **Data Analysis**: Sorting helps in organizing and summarizing data, making it easier to identify patterns, trends, and outliers. Searching enables quick retrieval of specific information from large datasets.

- **Algorithms and Data Structures**: Many algorithms and data structures rely on efficient sorting and searching techniques to achieve optimal performance. Examples include binary search, quicksort, and hash tables.

- **Data Visualization**: Sorting is often a prerequisite for creating meaningful visualizations, such as line plots, bar charts, and heatmaps. It allows for a logical and ordered representation of data.


Efficient sorting and searching algorithms can significantly reduce computation time and resource usage, especially when dealing with large datasets. NumPy, being a powerful library for numerical computing in Python, provides a set of optimized functions for sorting and searching arrays.


NumPy offers a range of efficient functions for sorting and searching arrays. These functions are implemented in optimized C code, making them much faster than their pure Python counterparts. Some of the key functions include:

- `np.sort()`: Sorts an array in ascending order along a specified axis. It returns a new sorted array, leaving the original array unchanged.

- `np.argsort()`: Returns the indices that would sort an array in ascending order. It is useful for obtaining the sorted order without actually sorting the array.

- `np.where()`: Returns the indices of elements in an array that satisfy a given condition. It is a versatile function for searching and filtering arrays based on specific criteria.

- `np.argmax()` and `np.argmin()`: Return the indices of the maximum and minimum elements in an array, respectively. They are useful for finding the positions of extreme values.


These functions, along with others available in NumPy, provide a powerful toolkit for efficient sorting and searching operations on arrays. They offer flexibility in terms of specifying the axis of operation, handling missing values, and performing complex data manipulations.


## [Sorting Arrays](#)

Sorting is a fundamental operation in data processing and analysis. NumPy provides several functions for sorting arrays efficiently. In this section, we will explore the `np.sort()` function and its variations for sorting arrays in ascending order, along specific axes, and in-place. We will also discuss `np.argsort()` for obtaining the indices of sorted elements and sorting in descending order.


<img src="../images/sorting-array.png" width="800">

### [`np.sort()`: Sorting Arrays in Ascending Order](#)


The `np.sort()` function is used to sort an array in ascending order. It returns a new sorted array, leaving the original array unchanged. Here's an example:


In [1]:
import numpy as np

In [2]:
arr = np.array([3, 1, 4, 2, 5])
arr

array([3, 1, 4, 2, 5])

In [3]:
sorted_arr = np.sort(arr)
sorted_arr

array([1, 2, 3, 4, 5])

In [4]:
arr

array([3, 1, 4, 2, 5])

The `np.sort()` function can also be used to sort multi-dimensional arrays. By default, it sorts the array along the last axis (row-wise for 2D arrays).


### [`np.sort()` with `axis` Parameter: Sorting Along Specific Axes](#)


The `np.sort()` function accepts an optional `axis` parameter that specifies the axis along which the sorting should be performed. By default, `axis=-1`, which sorts along the last axis.


In [5]:
arr = np.array([[3, 1, 4], [2, 5, 6]])
arr

array([[3, 1, 4],
       [2, 5, 6]])

In [6]:
sorted_arr = np.sort(arr, axis=0)
sorted_arr

array([[2, 1, 4],
       [3, 5, 6]])

In [7]:
sorted_arr = np.sort(arr, axis=1)
sorted_arr

array([[1, 3, 4],
       [2, 5, 6]])

In this example, `axis=0` specifies sorting along the first axis (column-wise for 2D arrays).


### [In-place Sorting with `arr.sort()`](#)

To sort an array in-place, modifying the original array, you can use the `sort()` method of the array itself. The `sort()` method does not return a new array but modifies the original array directly.


In [8]:
arr = np.array([3, 1, 4, 2, 5])
arr

array([3, 1, 4, 2, 5])

In [9]:
arr.sort()

In [10]:
arr

array([1, 2, 3, 4, 5])

The `sort()` method also accepts an optional `axis` parameter to specify the axis along which the sorting should be performed. By default, `axis=-1`, which sorts along the last axis.


In [11]:
arr = np.array([[3, 1, 4], [2, 5, 6]])
arr

array([[3, 1, 4],
       [2, 5, 6]])

In [12]:
arr.sort(axis=0)

In [13]:
arr

array([[2, 1, 4],
       [3, 5, 6]])

In [14]:
arr = np.array([[3, 1, 4], [2, 5, 6]])
arr

array([[3, 1, 4],
       [2, 5, 6]])

In [15]:
arr.sort(axis=1)

In [16]:
arr

array([[1, 3, 4],
       [2, 5, 6]])

In this example, `axis=0` specifies sorting along the first axis (column-wise for 2D arrays).


When a is an array with fields defined, this argument specifies which fields to compare first, second, etc. A single field can be specified as a string, and not all fields need be specified, but unspecified fields will still be used, in the order in which they come up in the dtype, to break ties.

In [17]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]


In [55]:
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype) # create a structured array

In [56]:
np.sort(a, order='height')

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [59]:
np.sort(a, order='age')

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

Thank you for pointing out the correction. I hope this clarifies the difference between `np.sort()` and `arr.sort()` for in-place sorting.

### [`np.argsort()`: Obtaining the Indices of Sorted Elements](#)


The `np.argsort()` function returns the indices that would sort an array in ascending order. It is useful when you need to obtain the sorted order without actually sorting the array.


In [19]:
arr = np.array([3, 1, 4, 2, 5])
arr

array([3, 1, 4, 2, 5])

In [20]:
sorted_indices = np.argsort(arr)
sorted_indices

array([1, 3, 0, 2, 4])

The resulting `sorted_indices` array contains the indices that would sort the original array in ascending order.


### [Sorting in Descending Order](#)


To sort an array in descending order, you can use the `np.sort()` function and then reverse the order of elements. Alternatively, you can use the `np.argsort()` function to obtain the indices of sorted elements in ascending order and then reverse the order of indices.


In [21]:
arr = np.array([3, 1, 4, 2, 5])
arr

array([3, 1, 4, 2, 5])

In [22]:
sorted_arr = np.sort(arr)[::-1]
sorted_arr

array([5, 4, 3, 2, 1])

Alternatively, you can use `np.argsort()` to obtain the indices that would sort the array in descending order and then use those indices to rearrange the array.


In [23]:
arr = np.array([3, 1, 4, 2, 5])
arr

array([3, 1, 4, 2, 5])

In [24]:
sorted_indices = np.argsort(arr)[::-1]
sorted_indices

array([4, 2, 0, 3, 1])

In [25]:
sorted_arr = arr[sorted_indices]
sorted_arr

array([5, 4, 3, 2, 1])

These examples demonstrate the flexibility and efficiency of NumPy's sorting functions. Whether you need to sort arrays in ascending or descending order, along specific axes, or obtain the indices of sorted elements, NumPy provides the necessary tools to accomplish these tasks with ease.

## [Searching and Filtering Techniques](#)

In addition to the searching functions discussed earlier, NumPy provides powerful techniques for searching and filtering arrays based on conditions, finding unique elements, and performing set operations. In this section, we will explore boolean indexing for filtering arrays based on conditions, `np.unique()` for searching unique elements, and set operations like intersection, union, and difference of arrays.


### [Boolean Indexing: Filtering Arrays Based on Conditions](#)


Boolean indexing is a technique that allows you to filter arrays based on conditions. It uses a boolean mask, which is an array of boolean values (True or False), to select elements from an array that satisfy a given condition.


In [26]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [27]:
mask = arr > 3
mask

array([False, False, False,  True,  True])

In [28]:
filtered_arr = arr[mask]
filtered_arr

array([4, 5])

In this example, `arr > 3` creates a boolean mask where elements greater than 3 are True and the rest are False. Using this mask as an index, `arr[mask]` selects only the elements that correspond to True values in the mask.


You can also combine multiple conditions using logical operators like `&` (and), `|` (or), and `~` (not):


In [29]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [30]:
mask = (arr > 2) & (arr < 5)
mask

array([False, False,  True,  True, False])

In [31]:
filtered_arr = arr[mask]
filtered_arr

array([3, 4])

In this case, `(arr > 2) & (arr < 5)` creates a boolean mask where elements that are both greater than 2 and less than 5 are True.


### [Finding Indices of Elements Satisfying Conditions](#)

The `np.where()` function is a versatile tool for searching and filtering arrays based on specified conditions. It returns the indices of elements that satisfy the given condition(s).


The basic syntax of `np.where()` is as follows:
```python
indices = np.where(condition)
```

Here, `condition` is a boolean array or a boolean expression that determines which elements to select. The function returns a tuple of arrays, one for each dimension, containing the indices of the elements that satisfy the condition.


Let's look at an example:

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
indices = np.where(arr % 2 == 0)
indices

(array([1, 3, 5, 7]),)

In [33]:
arr[indices]

array([2, 4, 6, 8])

In this example, `np.where(arr % 2 == 0)` returns the indices of the even elements in the array `arr`. The output is a tuple containing a single array with the indices `[1, 3, 5, 7]`.


You can also use `np.where()` with multiple conditions using logical operators such as `&` (and), `|` (or), and `~` (not). For example:

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
indices = np.where((arr > 3) & (arr < 8))
indices

(array([3, 4, 5, 6]),)

In [35]:
arr[indices]

array([4, 5, 6, 7])

Here, `np.where((arr > 3) & (arr < 8))` returns the indices of elements that are greater than 3 and less than 8.


Another useful feature of `np.where()` is its ability to provide different values based on the condition. The syntax for this is as follows:

```python
result = np.where(condition, x, y)
```


In this case, `result` will be an array of the same shape as the input arrays, where elements corresponding to `True` in the `condition` array will be taken from `x`, and elements corresponding to `False` will be taken from `y`.


Example:

In [36]:
arr = np.array([1, 2, 3, 4, 5])
result = np.where(arr < 3, 0, arr)
result

array([0, 0, 3, 4, 5])

In this example, elements of `arr` that are less than 3 are replaced with 0, while the remaining elements retain their original values.


The `np.where()` function is a powerful tool for searching and filtering arrays based on specific conditions, making it easier to extract desired elements or indices from an array.

### [Searching for Unique Elements with `np.unique()`](#)


The `np.unique()` function is used to find the unique elements in an array. It returns a sorted array of unique elements, eliminating any duplicates.


In [37]:
arr = np.array([1, 2, 2, 3, 4, 4, 5])
arr

array([1, 2, 2, 3, 4, 4, 5])

In [38]:
unique_arr = np.unique(arr)
unique_arr

array([1, 2, 3, 4, 5])

In this example, `np.unique(arr)` returns a sorted array of unique elements from `arr`, removing any duplicates.


You can also use the `return_counts` parameter to get the count of each unique element:


In [39]:
arr = np.array([1, 2, 2, 3, 4, 4, 5])
arr

array([1, 2, 2, 3, 4, 4, 5])

In [40]:
unique_arr, counts = np.unique(arr, return_counts=True)
unique_arr

array([1, 2, 3, 4, 5])

In [41]:
counts

array([1, 2, 1, 2, 1])

In this case, `np.unique(arr, return_counts=True)` returns both the unique elements and their corresponding counts.


### [Set Operations: Intersection, Union, and Difference of Arrays](#)


<img src="../images/set-operations.png" width="800">

NumPy provides functions for performing set operations on arrays, such as finding the intersection, union, and difference of arrays.

- `np.intersect1d(arr1, arr2)`: Returns the sorted, unique elements that are common to both `arr1` and `arr2`.
- `np.union1d(arr1, arr2)`: Returns the sorted, unique elements from both `arr1` and `arr2`.
- `np.setdiff1d(arr1, arr2)`: Returns the sorted, unique elements in `arr1` that are not in `arr2`.


In [42]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

In [43]:
np.intersect1d(arr1, arr2)

array([3, 4, 5])

In [44]:
np.union1d(arr1, arr2)

array([1, 2, 3, 4, 5, 6, 7])

In [45]:
np.setdiff1d(arr1, arr2)

array([1, 2])

In this example:
- `np.intersect1d(arr1, arr2)` returns the elements that are common to both `arr1` and `arr2`.
- `np.union1d(arr1, arr2)` returns the unique elements from both `arr1` and `arr2`.
- `np.setdiff1d(arr1, arr2)` returns the elements in `arr1` that are not in `arr2`.


These searching and filtering techniques in NumPy provide powerful ways to extract specific elements, filter arrays based on conditions, find unique elements, and perform set operations. They are essential tools for data analysis and manipulation tasks, allowing you to efficiently process and analyze large datasets.

## [(Optional) Sorting and Searching Performance](#)

When working with large datasets, the performance of sorting and searching operations becomes crucial. In this section, we will discuss the time complexity of sorting and searching operations in NumPy, techniques for optimizing their performance, and a comparison with Python's built-in sorting and searching functions.


### [Time Complexity of Sorting and Searching Operations](#)


Understanding the time complexity of sorting and searching operations is important for making informed decisions about which algorithm to use based on the size of the dataset.

- **Sorting Complexity**: The time complexity of sorting algorithms depends on the specific algorithm used. NumPy's `sort()` function uses a quicksort algorithm, which has an average time complexity of O(n log n) for arrays of size n. However, in the worst case, quicksort can have a time complexity of O(n^2) when the array is already sorted or nearly sorted.

- **Searching Complexity**: The time complexity of searching operations depends on the search algorithm and the size of the dataset. NumPy's `searchsorted()` function uses a binary search algorithm, which has a time complexity of O(log n) for arrays of size n. This makes it efficient for searching in large, sorted arrays.


It's important to note that the actual performance of sorting and searching operations may vary depending on factors such as the size of the array, the data type, and the specific implementation details.


### [Optimizing Sorting and Searching Performance](#)


To optimize the performance of sorting and searching operations in NumPy, consider the following techniques:

1. **Use appropriate data types**: Choose the appropriate data type for your arrays based on the nature of your data. Using smaller data types, such as `int32` instead of `int64`, can reduce memory usage and improve performance.

2. **Avoid unnecessary sorting**: If your data is already sorted or partially sorted, you can use specialized sorting algorithms like `np.sort(arr, kind='mergesort')` or `np.sort(arr, kind='heapsort')` that have better performance in such cases.

3. **Utilize sorting order**: If you need to perform multiple sorting operations on the same array, consider sorting it once and then using the sorted order for subsequent operations. This can save computation time.

4. **Use views instead of copies**: When possible, use array views instead of creating new copies of arrays. Views allow you to manipulate arrays without the overhead of copying data, which can improve performance.

5. **Leverage NumPy's optimized functions**: NumPy provides optimized functions for various operations, including sorting and searching. Using these functions instead of writing custom loops can significantly improve performance.

6. **Vectorize operations**: NumPy's vectorized operations are highly optimized and can perform computations much faster than explicit loops in Python. Whenever possible, use vectorized operations instead of iterating over arrays element by element.


### [Comparison with Python's Built-in Sorting and Searching Functions](#)


Python provides built-in sorting and searching functions, such as `sorted()` and `list.sort()` for sorting, and `in` operator for searching. However, NumPy's sorting and searching functions offer several advantages:

1. **Performance**: NumPy's functions are implemented in optimized C code, which makes them significantly faster than Python's built-in functions, especially for large arrays.

2. **Functionality**: NumPy's functions provide additional features and flexibility, such as sorting along specific axes, searching for insertion indices, and performing set operations on arrays.

3. **Memory efficiency**: NumPy's functions operate directly on arrays, avoiding the overhead of creating new lists or copying data, which can be more memory-efficient compared to Python's built-in functions.


However, it's worth noting that for small arrays or simple sorting and searching tasks, Python's built-in functions can be sufficient and may have comparable performance to NumPy's functions.


When deciding between using NumPy's functions or Python's built-in functions, consider factors such as the size of your data, the specific requirements of your task, and the need for additional functionality provided by NumPy.


In summary, understanding the time complexity of sorting and searching operations, utilizing optimization techniques, and leveraging NumPy's optimized functions can significantly improve the performance of your code when working with large datasets. NumPy's sorting and searching functions offer superior performance and functionality compared to Python's built-in functions, making them valuable tools for efficient data processing and analysis.

## [Summary and Conclusion](#)

In this lecture, we explored the sorting and searching capabilities of NumPy, a powerful library for numerical computing in Python. We delved into various functions and techniques for efficiently sorting arrays, searching for elements based on conditions, finding unique elements, and performing set operations.


Let's recap the key points covered in this lecture:

1. **Sorting Arrays**:
   - NumPy provides the `np.sort()` function for sorting arrays in ascending order, with options to sort along specific axes and perform in-place sorting.
   - The `np.argsort()` function returns the indices that would sort an array, allowing for indirect sorting and advanced indexing.
   - Sorting in descending order can be achieved by reversing the sorted array or using the indices returned by `np.argsort()`.

2. **Searching Arrays**:
   - The `np.where()` function is used to search for elements in an array based on conditions, returning the indices of elements that satisfy the given condition.
   - `np.argmax()` and `np.argmin()` functions find the indices of the maximum and minimum elements in an array, respectively.
   - `np.nonzero()` returns the indices of non-zero elements in an array.
   - `np.searchsorted()` finds the insertion indices for new elements in a sorted array, maintaining the sorted order.

3. **Searching and Filtering Techniques**:
   - Boolean indexing allows filtering arrays based on conditions using a boolean mask.
   - `np.unique()` function finds the unique elements in an array, with options to return counts of each unique element.
   - NumPy provides functions for set operations, such as `np.intersect1d()`, `np.union1d()`, and `np.setdiff1d()`, for finding the intersection, union, and difference of arrays.

4. **Sorting and Searching Performance**:
   - The time complexity of sorting algorithms, such as quicksort used by NumPy's `sort()` function, is O(n log n) on average, but can be O(n^2) in the worst case.
   - Searching algorithms, such as binary search used by NumPy's `searchsorted()` function, have a time complexity of O(log n) for sorted arrays.
   - Techniques for optimizing sorting and searching performance include using appropriate data types, avoiding unnecessary sorting, utilizing sorting order, using views instead of copies, leveraging NumPy's optimized functions, and vectorizing operations.
   - NumPy's sorting and searching functions offer superior performance and functionality compared to Python's built-in functions, especially for large arrays.


Remember, practice is key to mastering NumPy's sorting and searching functions. Experiment with different datasets, try out various techniques, and don't hesitate to refer to the documentation and community resources when you encounter challenges.
